### ISSUE TITLE
Finish 3 Use Cases

### ISSUE THREAD

**Issue by aahop** [abrisenomtz/ISQA3420#11]
One looks complete and another looks partially filled in, but we can finish all three.

**Comment by ckozeny** [comment]
Sounds good. Just got back into town, ill get them knocked out by the end of the night.

**Comment by ckozeny** [comment]
Anyone know of a way to add some spacing in the document? If i add a line or two in the document, it doesn't necessarily reflect that when its posted. Or find a way to just remove the numbers? It clutters it up quite a bit. Thanks!

**Comment by ckozeny** [comment]
Tried turning off wrapping and adding a few lines, didn't work. Turned tabs to spaces, again no luck. They'll be done regardless of whether the spacing is figured out, just would like to organize it a little better.

**Comment by aahop** [comment]
I'll take a look at it. Just make sure the content is there.

**Comment by ckozeny** [comment]
Added the other two use cases so everything is about wrapped up for those. Any modifications anyone would like to add, feel free.
