### ISSUE TITLE
Creating ERD Tables from Class

### ISSUE THREAD

**Issue by aahop** [abrisenomtz/ISQA3420#21]
As discussed in class 11/04/15

**Comment by aahop** [comment]
Consider how we should add CVE information to the given tables
-package level
-mandatory
-one or one to many?

**Comment by abrisenomtz** [comment]
![erd diagram](https://cloud.githubusercontent.com/assets/14810350/10950817/69ee6f56-82ff-11e5-9439-20106e2a86dc.PNG)

**Comment by abrisenomtz** [comment]
Add the CPE to the Package table , mandatory could have 0 to many.
