### ISSUE TITLE
Remove text in ERD as well as typo

### ISSUE THREAD

**Issue by ckozeny** [abrisenomtz/ISQA3420#26]
There is some text at the beginning of the ERD, when i edited it last i wasn't sure if that was pertinent to your diagram. Also, the last slot on the left column reads "Document document."

**Comment by abrisenomtz** [comment]
![erd_diagram](https://cloud.githubusercontent.com/assets/14810350/11412177/e4bc6f26-939e-11e5-9ed8-da39c97d86da.PNG)

**Comment by abrisenomtz** [comment]
The text has been removed and the typo is been fixed as well.
