### ISSUE TITLE
Attaching Image of DFD

### ISSUE THREAD

**Issue by aahop** [abrisenomtz/ISQA3420#4]
Not 100% sure how to get the image of our DFD into the file itself... "Drag and drop
 didn't work on the file itself, though it will for this issue? I'm not too experienced with GitHub. Any ideas appreciated. Otherwise, we can just use this tomorrow.
![dfd diagram 10 4](https://cloud.githubusercontent.com/assets/14914316/10270754/7c4be210-6ac1-11e5-9925-c1e23e3b23ef.png)

**Comment by abrisenomtz** [comment]
It only needed some additional elements to show the image, for further reference to upload an image to a file: 
1. Create a new issue and drag your image from your PC to the issue screen. 
2. Right-click in the image and copy the URL.
3. Open the file where you want to paste the image and type the following :  ! + ["Title for the image"] +("URL of the image") 

I already place the current DFD that Alex developed into the corresponding file. 

Thanks.
