### ISSUE TITLE
Create Templates / Decide Use Cases

### ISSUE THREAD

**Issue by aahop** [abrisenomtz/ISQA3420#8]
Create the template in the required format and decide what our 3 use cases will be.

**Comment by ckozeny** [comment]
Created the three templates for now. Planning to sift through the DFD and decide on a few to represent.

**Comment by ckozeny** [comment]
Went with Manage CPE Information (Daily Job), Manage Policy Information, and Manage Project Information for our use cases. Also filled in the primary actor and goal in context for each.
